name: CodeQL Analysis on Push

on:
 push:
    branches:
      - master

permissions:
 security-events: write
 contents: read
 actions: read

jobs:
 build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}